### ISSUE TITLE
Form widget not displaying saved value

### ISSUE THREAD

**Issue by kevin-invato** [responsiv/currency-plugin#52]
Hi,

I've encountered a bug in the Currency form widget. I saved a value in field 'price', and the value is present in the database, but the value is not showing in the form widget, it remains empty.

```
price:
  label: Prijs
  span: auto
  type: currency
``` 

October version: 3.7.10
Currency version: 2.1.0
Default value: EUR

Hopefully you can fix this issue.

Thanks in advance!

- Kevin
